spring:
  banner:
    location: classpath:banner.txt
  main:
    web-application-type: reactive

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:server-identity.jks
    key-password: secret
    key-store-password: secret
    trust-store: classpath:server-truststore.jks
    trust-store-password: secret
    client-auth: need
